# Generated by Django 3.1.5 on 2021-01-06 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indoorplants', '0002_auto_20210106_0141'),
        ('journal', '0002_entry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='plant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='indoorplants.plant'),
            preserve_default=False,
        ),
    ]
