# Generated by Django 3.1.5 on 2021-01-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_entry_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='journalimages/'),
        ),
    ]
