# Generated by Django 3.1.5 on 2021-01-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('watering', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('common_name', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('sunlight_type', models.CharField(blank=True, choices=[('Indirect', 'Indirect'), ('Direct', 'Direct')], default=None, max_length=8, null=True)),
                ('water_freq', models.CharField(blank=True, choices=[('D', 'check daily'), ('5', '3-5 days'), ('10', '7-10 days'), ('21', '14-21 days'), ('M', 'Monthly')], default=None, max_length=2, null=True)),
                ('soil_type', models.CharField(blank=True, choices=[('well-draining', 'well draining'), ('moisture-retaining', 'moisture retaining')], default=None, max_length=50, null=True)),
                ('moisture_level', models.CharField(blank=True, choices=[('Dry', 'Dry'), ('Damp', 'Damp'), ('Moist', 'Moist'), ('Wet', 'Wet')], default=None, max_length=5, null=True)),
                ('common_problems', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
