# Generated by Django 3.1.5 on 2021-01-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoorplants', '0002_auto_20210106_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttype',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('well draining', 'well draining'), ('moisture retaining', 'moisture retaining')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='planttype',
            name='water_freq',
            field=models.CharField(blank=True, choices=[('check daily', 'check daily'), ('3-5 days', '3-5 days'), ('7-10 days', '7-10 days'), ('14-21 days', '14-21 days'), ('Monthly', 'Monthly')], default=None, max_length=30, null=True),
        ),
    ]
