# Generated by Django 3.1.5 on 2021-01-07 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indoorplants', '0003_auto_20210106_1958'),
        ('indoorplants', '0003_auto_20210106_2335'),
    ]

    operations = [
    ]
