# Generated by Django 3.1.5 on 2021-01-09 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indoorplants', '0004_merge_20210107_0007'),
        ('plantcalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCalendarEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoorplants.plant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='plantmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='plantmember',
            name='task',
        ),
        migrations.RemoveField(
            model_name='plantmember',
            name='user',
        ),
        migrations.DeleteModel(
            name='PlantCalendar',
        ),
        migrations.DeleteModel(
            name='PlantMember',
        ),
    ]
