# Generated by Django 3.1.5 on 2021-01-12 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indoorplants', '0004_merge_20210107_0007'),
        ('plantcalendar', '0002_auto_20210109_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantWateringEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoorplants.plant')),
            ],
        ),
    ]
