from indoorplants.models import PlantType, Plant
from myuser.models import MyUser
# from django.core.management.base import BaseCommand


def generate_data_planttype():
  library_data = [
    {
    "name":'Pothos',
    "common_name":'',
    "photo":'images/pothos.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'7-10 days',
    'soil_type':'well draining',
    'moisture_level':'Damp',
    'common_problems':'Stunted Growth due to insect infestation',
    'notes':'',
    },
    {
    'name':'Aglaonema',
    'common_name':'Chinese Evergreen',
    'photo':'images/aglaonema.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'7-10 days',
    'soil_type':'well draining',
    'moisture_level':'Damp',
    'common_problems':'Drooping leaves (needs water) or yellowing leaves (over watered)',
    'notes':'water when soil is dry to touch',
    },
    {
    'name':'CRASSULA ovata',
    'common_name':'Jade Plant',
    'photo':'images/jade-plant.jpg',
    'sunlight_type':'Direct',
    'water_freq':'check daily',
    'soil_type':'moisture retaining',
    'moisture_level':'Damp',
    'common_problems':'losing leaves means it needs watering',
    'notes':'',
    },
    {
    'name':'Asparagus setaceus',
    'common_name':'Asparagus Fern',
    'photo':'images/Asparagus-fern.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'check daily',
    'soil_type':'well draining',
    'moisture_level':'Damp',
    'common_problems':'Brown or droopy leaves means it needs water',
    'notes':'For a heathy plant mist leaves with water daily',
    },
    {
    'name':'Pilea peperomioides',
    'common_name':'Chinese Money Plant',
    'photo':'images/money-plant.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'7-10 days',
    'soil_type':'well draining',
    'moisture_level':'Damp',
    'common_problems':'Droopy leaves means it needs watering',
    'notes':'Do not let soil completely dry out',
    },
    {
    'name':'Yucca',
    'common_name':'',
    'photo':'images/yucca.jpeg',
    'sunlight_type':'Direct',
    'water_freq':'14-21 days',
    'soil_type':'well draining',
    'moisture_level':'Dry',
    'common_problems':'Overwatering',
    'notes':'Only water once soil throughout the pot is completely dry.',
    },
    {
    'name':'Air Plants',
    'common_name':'',
    'photo':'images/air-plants.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'7-10 days',
    'soil_type':'',
    'moisture_level':'',
    'common_problems':'Prone to pest and fungus infestations.',
    'notes':'When watering place the plant in a bowl of water for about 2 hours.',
    },
    {
    'name':'Chlorophytum comosum',
    'common_name':'Spider Plants',
    'photo':'images/spider-plant.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'7-10 days',
    'soil_type':'well draining',
    'moisture_level':'Damp',
    'common_problems':'Tips of the leaves turn brown due to mineral build up in the soil.',
    'notes':'Use filtered water.',
    },
    {
    'name':'SPATHIPHYLLUM',
    'common_name':'Peace Lily',
    'photo':'images/Peace-Lily.jpeg',
    'sunlight_type':'Indirect',
    'water_freq':'3-5 days',
    'soil_type':'well draining',
    'moisture_level':'Moist',
    'common_problems':'Tips of the leaves turn brown.',
    'notes':'Use filtered water',
    },
    {
    'name':'Aloe Vera',
    'common_name':'Aloe',
    'photo':'images/Aloe.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'14-21 days',
    'soil_type':'well draining',
    'moisture_level':'Damp',
    'common_problems':'Root rot',
    'notes':'Do not overwater, wait until the top third of the soil is completely dry.',
    },
    {
    'name':'Hedera helix',
    'common_name':'English Ivy',
    'photo':'images/english-ivy.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'7-14 days',
    'soil_type':'well draining',
    'moisture_level':'Moist',
    'common_problems':'Becomes infested with aphids or spider mites.',
    'notes':'Mist neem oil on top and bottom of the leaves.',
    },
    {
    'name':'Dracaena Marginata',
    'common_name':'Dragon Tree',
    'photo':'images/Dragon-tree.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'7-14 days',
    'soil_type':'well draining',
    'moisture_level':'Moist',
    'common_problems':'',
    'notes':'Test the top third of the soil before water. If it is dry then you can water it.',
    },
    {
    'name':'Calathea zebrina',
    'common_name':'Zebra Plant',
    'photo':'images/Zebra-Plant.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'7-10 days',
    'soil_type':'moisture retaining',
    'moisture_level':'Moist',
    'common_problems':'Root rot from over-watering.',
    'notes':'Test the top third of the soil for dryness before water',
    },
    {
    'name':'Ficus elastic',
    'common_name':'Rubber Plant',
    'photo':'images/rubber-plant.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'14-21 days',
    'soil_type':'well draining',
    'moisture_level':'Damp',
    'common_problems':'Leaves turn yellow or brown caused from over-watering.',
    'notes':'',
    },
    {
    'name':'Bromeliad',
    'common_name':'',
    'photo':'images/Bromeliad.jpeg',
    'sunlight_type':'Indirect',
    'water_freq':'Monthly',
    'soil_type':'well draining',
    'moisture_level':'Dry',
    'common_problems':'Over-watering',
    'notes':'Let soil completely dry out between watering.',
    },
    {
    'name':'Kalanchoe',
    'common_name':'',
    'photo':'images/kalanchoe.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'14-21 days',
    'soil_type':'well draining',
    'moisture_level':'Dry',
    'common_problems':'Over-watering',
    'notes':'In the winter months you may not need to water as often.',
    },
    {
    'name':'Beaucarnea recurvata',
    'common_name':'Ponytail Palm',
    'photo':'images/Ponytail.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'Monthly',
    'soil_type':'well draining',
    'moisture_level':'Dry',
    'common_problems':'Over-watering',
    'notes':'May need to water less in the winter months.',
    },
    {
    'name':'Phalaenopsis spp',
    'common_name':'Phalaenopsis Orchid',
    'photo':'images/phalaenopsis-orchid.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'3-5 days',
    'soil_type':'well draining',
    'moisture_level':'Moist',
    'common_problems':'',
    'notes':'',
    },
    {
    'name':'Philodendron',
    'common_name':'',
    'photo':'images/Philodendron.JPG',
    'sunlight_type':'Indirect',
    'water_freq':'7-10 days',
    'soil_type':'well draining',
    'moisture_level':'Moist',
    'common_problems':'',
    'notes':'',
    },
    {
    'name':'Euphorbia milii',
    'common_name':'Crown of Thorns',
    'photo':'images/crown-of-thrones.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'7-10 days',
    'soil_type':'well draining',
    'moisture_level':'Damp',
    'common_problems':'Leaves turn yellow or begin begin to fall off sign of it needs water.',
    'notes':'Make sure it is getting plenty of indrect sunlight',
    },
    {
    'name':'Schlumbergera bridgessii',
    'common_name':'Christmas Cactus',
    'photo':'images/Christmas-Cactus.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'7-10 days',
    'soil_type':'well draining',
    'moisture_level':'Moist',
    'common_problems':'Over-watering',
    'notes':'',
    },
    {
    'name':'Zamioculcas zamiifolia',
    'common_name':'ZZ Plant',
    'photo':'images/zz-plant.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'7-10 days',
    'soil_type':'well draining',
    'moisture_level':'Damp',
    'common_problems':'Prone to aphid infestation and over watering.',
    'notes':'',
    },
    {
    'name':'Dracaena trifasciata',
    'common_name':'Snake Plant',
    'photo':'images/snake-plant.jpeg',
    'sunlight_type':'Indirect',
    'water_freq':'Monthly',
    'soil_type':'well draining',
    'moisture_level':'Dry',
    'common_problems':'Over-watering',
    'notes':'',
    },
    {
    'name':'Schefflera',
    'common_name':'',
    'photo':'images/Schefflera.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'7-10 days',
    'soil_type':'well draining',
    'moisture_level':'Moist',
    'common_problems':'Yellowing leaves means its being over-watered',
    'notes':'',
    },
    {
    'name':'Dieffenbachia',
    'common_name':'Dumb Cane',
    'photo':'images/Dieffenbachia.jpg',
    'sunlight_type':'Indirect',
    'water_freq':'7-10 days',
    'soil_type':'well draining',
    'moisture_level':'Moist',
    'common_problems':'Prone to spider mites',
    'notes':'Mist leaves with neem oil to help keep away spider mites.',
    },

  ]

  for plant_type in library_data:
      try:
          PlantType.objects.create(
            name=plant_type['name'],
            common_name=plant_type['common_name'],
            photo=plant_type['photo'],
            sunlight_type=plant_type['sunlight_type'],
            water_freq=plant_type['water_freq'],
            soil_type=plant_type['soil_type'],
            moisture_level=plant_type['moisture_level'],
            common_problems=plant_type['common_problems'],
            notes=plant_type['notes']
          )
      except Exception as e:
          print(e)

  

def generate_data_plant():
  plant_list = [
    # list the name of the plant type here
    'Pothos',
    'Aglaonema',
    'CRASSULA ovata',
    'Asparagus setaceus',
    'Pilea peperomioides',
    'Yucca',
    'Air Plants',
    'Chlorophytum comosum',
    'SPATHIPHYLLUM',
    'Aloe Vera',
    'Hedera helix',
    'Dracaena Marginata',
    'Calathea zebrina',
    'Ficus elastic',
    'Bromeliad',
    'Kalanchoe',
    'Beaucarnea recurvata',
    'Phalaenopsis spp',
    'Philodendron',
    'Euphorbia milii',
    'Schlumbergera bridgessii',
    'Zamioculcas zamiifolia',
    'Dracaena trifasciata',
    'Schefflera',
    'Dieffenbachia'
    ]
  for plant in plant_list:
      try:
          Plant.objects.create(
            planttype=PlantType.objects.get(name=plant),
            owner=MyUser.objects.get(username="admin")
          )
      except Exception as e:
          print(e)
